### ISSUE TITLE
Single keybindings `l`,`h`,etc action doesn't occur until another key is pressed

### ISSUE THREAD

**Issue by excetara2** [aziz/SublimeFileBrowser#108] opened 2016-04-05 06:16 UTC
When I am in the dired mode the commands `l`, `h`, `j`, or any single letter command just pauses and waits for another command to be input before performing the action. I can see this with sublime.log_commands(). Pressing `l` will do nothing until I press another key for example `ctrl+n` which I have set to scroll down one line. Then it will collapse the folder and go down one line at the same time.

I am running on MacOSX and using the sublemacs package for keybindings so not sure if this is conflicting but it shouldn't be as none of the bindings are the same. Is this the normal behavior or is something on my system conflicting with the bindings to cause the pause?

**Comment by vovkkk** [comment] 2016-04-05 06:50
It is not normal, and I cannot reproduce it on Windows 8.1, even with sublemacspro installed.

Interesting, similar issue was reported recently in https://github.com/aziz/PlainTasks/issues/271 and @sdaza uses OSX too, it seems.

Try to disable sublemacspro by adding it into ignore list in main preferences, restart ST; if it is not the reason, try on clean profile.

**Comment by excetara2** [comment] 2016-04-05 09:25
I figured out Autospell is the culprit using FindKeyConflicts because of a keybinding conflict. I have just removed the package and it works fine. I also can't use the copy, move, and paste commands. The bindings from sublemacs takeover these in the dired windows. I think it overwrites the emacs bindings and the regular super bindings so it just does a regular copy, paste, and cut not the dired versions. Is there a way to tell it to overwrite the super copy, cut, and paste commands just in the Dired mode windows or context? Maybe I can just set the copy, cut and paste to different bindings and all should be fine.

**Comment by excetara2** [comment] 2016-04-05 09:47
Nevermind if I copy over the bindings for `super` into my user key bindings it works properly in the file windows with copy, cut, and paste. Cheers for the help

**Comment by vovkkk** [comment] 2016-04-05 09:50
Er, slow typing, still worth to mention that ST takes keybinding files in certain order http://docs.sublimetext.info/en/latest/extensibility/packages.html#merging-and-order-of-precedence

I’m not sure what you mean by `super`, but if all work let’s close it.

**Closed by vovkkk** 2016-04-05 09:50 UTC
Labels: invalid

**Comment by excetara2** [comment] 2016-04-05 09:52
Sorry only recently switched to mac so meant using the command key but `super+c` and `super+v` that you have set in the default key bindings. I just copied them to the keybindings for the user which I'd presume are read last. Yes it is closed.

**Comment by vovkkk** [comment] 2016-04-05 10:20
:smile: too many contexts, you meant ⌘, I thought about super in Python

Speaking of Autospell, I think it can be fixed on their side, if it matters, suggest checking if view is editable (it is easy via ST API), and do not operate in read-only view, theoretically it should be possible.
